#!/usr/bin/env bash
# scripts/post_images_report.sh
#
# Posts a PR comment with a download link and table of generated scenario
# images and architecture diagrams.  Exits silently when PR_NUMBER is not
# set (e.g. workflow_dispatch without a PR).
#
# Usage: bash scripts/post_images_report.sh
#
# Required environment variables:
#   GH_TOKEN           GitHub token with pull-requests:write permission
#   PR_NUMBER          Pull request number (unset → skip comment)
#   ARTIFACT_URL       Download URL for the generated-images bundle artifact
#
# Automatically available in GitHub Actions (no need to set explicitly):
#   GITHUB_REPOSITORY  Owner/repo  (e.g. alexandrelheinen/arco)
#   GITHUB_SERVER_URL  https://github.com
#   GITHUB_RUN_ID      Workflow run ID
#
# Exit code: 0 always (comment posting is best-effort).

set -euo pipefail

if [ -z "${PR_NUMBER:-}" ]; then
    echo "No PR_NUMBER set – skipping comment."
    exit 0
fi

# Derive the human-readable label (e.g. pr42) from the PR number.
REF="pr${PR_NUMBER}"

ARTIFACT_URL="${ARTIFACT_URL:-}"
RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

if [ -n "$ARTIFACT_URL" ]; then
    DOWNLOAD_LINE="📦 **[Download all images](${ARTIFACT_URL})**"
else
    DOWNLOAD_LINE="📦 **[View workflow run](${RUN_URL})**"
fi

BODY="## 📊 Generated Images

Scenario examples and architecture diagrams have been generated for this PR.

${DOWNLOAD_LINE}

| Group | Image | Description |
|-------|-------|-------------|
| Example | \`arcoex_astar_${REF}.png\` | A* graph scenario (2-D) |
| Example | \`arcoex_ppp_${REF}.png\` | PPP warehouse scenario (3-D) |
| Example | \`arcoex_rr_${REF}.png\` | RR arm scenario (2-D) |
| Example | \`arcoex_city_${REF}.png\` | City race scenario (2-D) |
| Example | \`arcoex_vehicle_${REF}.png\` | Vehicle benchmark scenario (2-D, RRT* vs SST) |
| Example | \`arcoex_rrp_${REF}.png\` | RRP SCARA arm scenario (3-D) |
| Example | \`arcoex_occ_${REF}.png\` | OCC piano movers scenario (2-D) |
| Pyreverse | \`pyreverse_classes.png\` | Class diagram showing inheritance and relationships |
| Pyreverse | \`pyreverse_packages.png\` | Package structure and dependencies |

_Generated by [workflow run](${RUN_URL})_"

echo "Posting comment to PR #${PR_NUMBER}..."
echo "$BODY" | jq -Rs '{"body": .}' | \
    gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        "/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
        --input -

echo "✅  Comment posted."
