#!/usr/bin/env bash
# scripts/post_smoke_report.sh
#
# Reads per-scenario smoke test result files and posts a summary comment on
# the pull request.  Exits silently when PR_NUMBER is not set (e.g. push
# to main or workflow_dispatch without a PR).
#
# Usage: bash scripts/post_smoke_report.sh <results_dir>
#
# Required environment variables:
#   GH_TOKEN           GitHub token with pull-requests:write permission
#   PR_NUMBER          Pull request number (unset → skip comment)
#
# Automatically available in GitHub Actions (no need to set explicitly):
#   GITHUB_REPOSITORY  Owner/repo  (e.g. alexandrelheinen/arco)
#   GITHUB_SERVER_URL  https://github.com
#   GITHUB_RUN_ID      Workflow run ID
#
# Exit code: 0 always (comment posting is best-effort).

set -euo pipefail

RESULTS_DIR="${1:?Usage: $0 <results_dir>}"

SCENARIOS=(astar city rr vehicle ppp rrp occ)

if [ -z "${PR_NUMBER:-}" ]; then
    echo "No PR_NUMBER set – skipping comment."
    exit 0
fi

echo "=== Building smoke test report ==="

TABLE_ROWS=""
ALL_PASS=true
for SCENARIO in "${SCENARIOS[@]}"; do
    RESULT_FILE="${RESULTS_DIR}/smoke_result_${SCENARIO}.txt"
    if [ -f "$RESULT_FILE" ]; then
        CONTENT="$(tr -d '[:space:]' < "$RESULT_FILE")"
        if [ "$CONTENT" = "pass" ]; then
            STATUS="✅ pass"
        else
            STATUS="❌ fail"
            ALL_PASS=false
        fi
    else
        STATUS="❌ fail"
        ALL_PASS=false
    fi
    TABLE_ROWS="${TABLE_ROWS}| \`${SCENARIO}\` | ${STATUS} |
"
done

if $ALL_PASS; then
    SUMMARY="✅ All smoke tests passed"
else
    SUMMARY="❌ Some smoke tests failed"
fi

RUN_URL="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

BODY="## 🔥 Smoke Test Results

${SUMMARY}

| Scenario | Result |
|----------|--------|
${TABLE_ROWS}
_Generated by [workflow run](${RUN_URL})_"

echo "Posting comment to PR #${PR_NUMBER}..."
echo "$BODY" | jq -Rs '{"body": .}' | \
    gh api \
        --method POST \
        -H "Accept: application/vnd.github+json" \
        "/repos/${GITHUB_REPOSITORY}/issues/${PR_NUMBER}/comments" \
        --input -

echo "✅  Comment posted."
