[package]
name = "arco-guidance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Interpolation, motion primitives and vehicle models."

[dependencies]
arco-core.workspace = true
arco-control.workspace = true

[lints]
workspace = true

